# Generated by Django 6.0.3 on 2026-03-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_clinic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]

